#!/bin/bash

echo "📧 Gmail SMTP Setup Helper"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ Functions already updated with Gmail FROM address"
echo ""
echo "📋 NEXT STEPS:"
echo ""
echo "1. Enable 2-Step Verification:"
echo "   https://myaccount.google.com/security"
echo ""
echo "2. Create App Password:"
echo "   https://myaccount.google.com/apppasswords"
echo "   - Name it: 'Voyager Travel Planner'"
echo "   - Copy the 16-character password"
echo ""
echo "3. Configure Firebase Extension:"
echo "   https://console.firebase.google.com/project/voyagerai-travel-planner/extensions"
echo ""
echo "   SMTP URI format (remove spaces from app password!):"
echo "   smtps://feedmyinfo@gmail.com:YOUR-APP-PASSWORD@smtp.gmail.com:465"
echo ""
echo "   Default FROM:"
echo "   feedmyinfo@gmail.com"
echo ""
echo "4. After extension is configured, deploy functions:"
echo "   firebase deploy --only functions:onTripCreated,functions:onTripUpdated,functions:onTripDeleted --project voyagerai-travel-planner"
echo ""
echo "5. Test:"
echo "   node send-test-email.cjs"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "Full guide available in: GMAIL_SETUP.md"
echo ""

